export const headCells = [
  {
    id: "id",
    numeric: false,
    disablePadding: true,
    label: "ID",
    sortable: true,
  },
  {
    id: "name",
    numeric: false,
    disablePadding: true,
    label: "Tên sản phẩm",
    sortable: true,
  },
  {
    id: "img",
    numeric: false,
    disablePadding: false,
    label: "Ảnh",
    sortable: false,
  },
  {
    id: "description",
    numeric: false,
    disablePadding: false,
    label: "Chi tiết",
    sortable: false,
  },
  {
    id: "quantity",
    numeric: false,
    disablePadding: false,
    label: "Số lượng",
    sortable: true,
  },
  {
    id: "status",
    numeric: false,
    disablePadding: false,
    label: "Trạng thái",
    sortable: false,
  },
  {
    id: "productType",
    numeric: false,
    disablePadding: true,
    label: "Kiểu",
    sortable: true,
  },
  {
    id: "action",
    numeric: false,
    disablePadding: true,
    label: "Action",
    sortable: false,
  },
]
